DROP TABLE IF EXISTS Node_tag;
DROP TABLE IF EXISTS Way_tag;
DROP TABLE IF EXISTS Relation_tag;
DROP TABLE IF EXISTS Node;
DROP TABLE IF EXISTS Tag;
DROP TABLE IF EXISTS Way;
DROP TABLE IF EXISTS Relation;

CREATE TABLE Node(
    id BIGINT NOT NULL PRIMARY KEY,
	lon DOUBLE PRECISION NOT NULL,
    lat DOUBLE PRECISION NOT NULL,
    username VARCHAR(256) NOT NULL
);

CREATE TABLE Tag(
    id SERIAL NOT NULL PRIMARY KEY,
    k VARCHAR(256) NOT NULL,
    v VARCHAR(256) NOT NULL
);

CREATE TABLE Way(
    id BIGINT NOT NULL PRIMARY KEY,
    username VARCHAR(256) NOT NULL
);

CREATE TABLE Relation(
    id BIGINT NOT NULL PRIMARY KEY,
    username VARCHAR(256) NOT NULL
);

CREATE TABLE Node_tag(
  nodes_id BIGINT NOT NULL,
  tags_id BIGINT NOT NULL,
  FOREIGN KEY (nodes_id) REFERENCES Node(id) ON DELETE CASCADE,
  FOREIGN KEY (tags_id) REFERENCES Tag(id) ON DELETE CASCADE
);

CREATE TABLE Way_tag(
  ways_id BIGINT NOT NULL,
  tags_id BIGINT NOT NULL,
  FOREIGN KEY (ways_id) REFERENCES Way(id) ON DELETE CASCADE,
  FOREIGN KEY (tags_id) REFERENCES Tag(id) ON DELETE CASCADE
);

CREATE TABLE Relation_tag(
  relations_id BIGINT NOT NULL,
  tags_id BIGINT NOT NULL,
  FOREIGN KEY (relations_id) REFERENCES Relation(id) ON DELETE CASCADE,
  FOREIGN KEY (tags_id) REFERENCES Tag(id) ON DELETE CASCADE
);